apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n-test
  labels:
    app: n8n
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5678