apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n-sts
  labels: 
    app: postgres-deploy
type: Opaque
stringData:
  PG_DATA: "/data/pgdata"
  POSTGRES_DB: "postgresdb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin123"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_DATABASE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres-service"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: "postgres"
  DB_POSTGRESDB_PASSWORD: "admin123"
  